-- ============================================
-- Migration: Fix learning_progress unique constraint to use learner_id
-- Created: 2024-12
-- Description: Change unique constraint from (user_id, learning_point_id, tier) 
--              to (learner_id, learning_point_id, tier) to support multi-learner
--              progress tracking where the same parent can mine the same word
--              for different learners.
-- ============================================

-- Step 1: Drop the old constraint
-- Note: The actual constraint name may be auto-generated by PostgreSQL
-- Try both the explicit name and the auto-generated name
ALTER TABLE public.learning_progress 
DROP CONSTRAINT IF EXISTS uq_user_learning_point_tier;

ALTER TABLE public.learning_progress 
DROP CONSTRAINT IF EXISTS learning_progress_user_id_learning_point_id_tier_key;

-- Step 2: Create a new unique constraint on (learner_id, learning_point_id, tier)
-- Note: This uses a partial unique index to handle NULL learner_id (legacy rows)
-- For rows where learner_id IS NOT NULL, enforce uniqueness per learner
-- For rows where learner_id IS NULL, we'll rely on the user_id check in application logic
CREATE UNIQUE INDEX IF NOT EXISTS uq_learner_learning_point_tier 
ON public.learning_progress(learner_id, learning_point_id, tier)
WHERE learner_id IS NOT NULL;

-- Step 3: For legacy rows (learner_id IS NULL), keep a constraint on (user_id, learning_point_id, tier)
-- This ensures backward compatibility for any rows that might still have NULL learner_id
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_learning_point_tier_legacy
ON public.learning_progress(user_id, learning_point_id, tier)
WHERE learner_id IS NULL;

-- Step 4: Verify indexes were created
-- SELECT indexname, indexdef 
-- FROM pg_indexes 
-- WHERE tablename = 'learning_progress' 
--   AND indexname IN ('uq_learner_learning_point_tier', 'uq_user_learning_point_tier_legacy');

